---
title: "InfoSci00.Rmd"
author: "Robert A. Stevens"
date: "August 25, 2016"
output: html_document
---

*Information Science*

by David G. Luenberger

http://press.princeton.edu/TOCs/c8214.html

# TABLE OF CONTENTS:

Preface

Chapter 1: INTRODUCTION  
1.1 Themes of Analysis  
1.2 Information Lessons

Part I: ENTROPY: The Foundation of Information 

Chapter 2: INFORMATION DEFINITION  
2.1 A Measure of Information  
2.2 The Definition of Entropy  
2.3 Information Sources  
2.4 Source Combinations  
2.5 Bits as a Measure  
2.6 About Claude E. Shannon  
2.7 Exercises  
2.8 Bibliography

Chapter 3: CODES  
3.1 The Coding Problem  
3.2 Average Code Length and Entropy  
3.3 Shannon's First Theorem  
3.4 Exercises  
3.5 Bibliography

Chapter 4: COMPRESSION  
4.1 Huffman Coding  
4.2 Intersymbol Dependency  
4.3 Lempel-Ziv Coding  
4.4 Other Forms of Compression  
4.5 Exercises  
4.6 Bibliography

Chapter 5: CHANNELS  
5.1 Discrete Channel  
5.2 Conditional and Joint Entropies  
5.3 Flipping a Channel  
5.4 Mutual Information  
5.5 Capacity*  
5.6 Shannon's Second Theorem*  
5.7 Exercises  
5.8 Bibliography

Chapter 6: ERROR-CORRECTING CODES  
6.1 Simple Code Concepts  
6.2 Hamming Distance  
6.3 Hamming Codes  
6.4 Linear Codes  
6.5 Low-Density Parity Check Codes  
6.6 Interleaving  
6.7 Convolutional Codes  
6.8 Turbo Codes  
6.9 Applications  
6.10 Exercises  
6.11 Bibliography  
Summary of Part I

Part II: ECONOMICS: Strategies for Value 

Chapter 7: MARKETS  
7.1 Demand  
7.2 Producers  
7.3 Social Surplus  
7.4 Competition  
7.5 Optimality of Marginal Cost Pricing  
7.6 Linear Demand Curves  
7.7 Copyright and Monopoly  
7.8 Other Pricing Methods  
7.9 Oligopoly  
7.10 Exercises  
7.11 Bibliography

Chapter 8: PRICING SCHEMES  
8.1 Discrimination  
8.2 Versions  
8.3 Bundling  
8.4 Sharing  
8.5 Exercises  
8.6 Bibliography  

Chapter 9: VALUE  
9.1 Conditional Information  
9.2 Informativity and Generalized Entropy*  
9.3 Decisions  
9.4 The Structure of Value  
9.5 Utility Functions*  
9.6 Informativity and Decision Making*  
9.7 Exercises  
9.8 Bibliography

Chapter 10: INTERACTION  
10.1 Common Knowledge  
10.2 Agree to Disagree?  
10.3 Information and Decisions  
10.4 A Formal Analysis*  
10.5 Metcalfe's Law  
10.6 Network Economics*  
10.7 Exercises  
10.8 Bibliography  
Summary of Part II

Part III: ENCRYPTION: Security through Mathematics 

Chapter 11: CIPHERS
11.1 Definitions  
11.2 Example Ciphers  
11.3 Frequency Analysis  
11.4 Cryptograms  
11.5 The Vigenére Cipher  
11.6 The Playfair Cipher  
11.7 Homophonic Codes  
11.8 Jefferson's Wheel Cipher  
11.9 The Enigma Machine  
11.10 The One-Time Pad  
11.11 Exercises  
11.12 Bibliography

Chapter 12: CRYPTOGRAPHY THEORY  
12.1 Perfect Security  
12.2 Entropy Relations  
12.3 Use of a One-Time Pad*  
12.4 The DES and AES Systems  
12.5 Exercises  
12.6 Bibliography

Chapter 13: PUBLIC KEY CRYPTOGRAPHY  
13.1 A Basic Dilemma  
13.2 One-Way Functions  
13.3 Discrete Logarithms  
13.4 Diffie-Hellman Key Exchange  
13.5 Modular Mathematics  
13.6 Alternative Puzzle Solution  
13.7 RSA  
13.8 Square and Multiply*  
13.9 Finding Primes*  
13.10 Performance*  
13.11 The Future  
Appendix: The Extended Euclidean Algorithm  
13.12 Exercises  
13.13 Bibliography  

Chapter 14: SECURITY PROTOCOLS  
14.1 Digital Signatures  
14.2 Blinded Signatures  
14.3 Digital Cash  
14.4 Identification  
14.5 Zero-Knowledge Proofs  
14.6 Smart Cards  
14.7 Exercises  
14.8 Bibliography  
Summary of Part III

Part IV: EXTRACTION: Information from Data 

Chapter 15: DATA STRUCTURES  
15.1 Lists  
15.2 Trees  
15.3 Traversal of Trees  
15.4 Binary Search Trees (BST)  
15.5 Partially Ordered Trees  
15.6 Tries*  
15.7 Basic Sorting Algorithms  
15.8 Quicksort  
15.9 Heapsort  
15.10 Merges  
15.11 Exercises  
15.12 Bibliography  

Chapter 16: DATABASE SYSTEMS  
16.1 Relational Structure  
16.2 Keys  
16.3 Operations  
16.4 Functional Dependencies  
16.5 Normalization  
16.6 Joins and Products*  
16.7 Database Languages  
16.8 Exercises  
16.9 Bibliography  

Chapter 17: INFORMATION RETRIEVAL  
17.1 Inverted Files  
17.2 Strategies for Indexing  
17.3 Inverted File Compression*  
17.4 Queries  
17.5 Ranking Methods  
17.6 Network Rankings  
17.7 Exercises  
17.8 Bibliography

Chapter 18: DATA MINING  
18.1 Overview of Techniques  
18.2 Market Basket Analysis  
18.3 Least-Squares Approximation  
18.4 Classification Trees  
18.5 Bayesian Methods  
18.6 Support Vector Machines  
18.7 Other Methods  
18.8 Exercises  
18.9 Bibliography  
Summary of Part IV

Part V: EMISSION: The Mastery of Frequency 

Chapter 19: FREQUENCY CONCEPTS  
19.1 The Telegraph  
19.2 When Dots Became Dashes  
19.3 Fourier Series  
19.4 The Fourier Transform  
19.5 Thomas Edison and the Telegraph  
19.6 Bell and the Telephone  
19.7 Lessons in Frequency  
19.8 Exercises  
19.9 Bibliography

Chapter 20: RADIO WAVES  
20.1 Why Frequencies?  
20.2 Resonance  
20.3 The Birth of Radio  
20.4 Marconi's Radio  
20.5 The Spark Bandwidth  
20.6 The Problems  
20.7 Continuous Wave Generation  
20.8 The Triode Vacuum Tube  
20.9 Modulation Mathematics  
20.10 Heterodyne Principle  
20.11 Frequency Modulation  
20.12 Exercises  
20.13 Bibliography  

Chapter 21: SAMPLING AND CAPACITY  
21.1 Entropy  
21.2 Capacity of the Gaussian Channel  
21.3 Sampling Theorem  
21.4 Generalized Sampling Theorem*  
21.5 Thermal Noise  
21.6 Capacity of a Band-Limited Channel  
21.7 Spread Spectrum  
21.8 Spreading Technique  
21.9 Multiple Access Systems  
21.10 Exercises  
21.11 Bibliography

Chapter 22: NETWORKS  
22.1 Poisson Processes  
22.2 Frames  
22.3 The ALOHA System  
22.4 Carrier Sensing  
22.5 Routing Algorithms  
22.6 The Bellman-Ford Algorithm  
22.7 Distance Vector Routing  
22.8 Dijkstra's Algorithm  
22.9 Other Issues  
22.10 Exercises  
22.11 Bibliography  
Summary of Part V

Index

Also see

http://web.mit.edu/6.02/www/currentsemester/handouts.shtml

http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/lecture-notes/

http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-011-introduction-to-communication-control-and-signal-processing-spring-2010/readings/
